### ISSUE TITLE
Failed to run sample command 'aflize bison'

### ISSUE THREAD

**Issue by kcwu** [d33tah/aflize#2] opened 2016-02-15 06:07 UTC
failed to run sample command

```
(inside d33tah/afl-sid of image version id 99e736835753)
# aflize bison
```

```
Mon Feb 15 05:54:03 2016: Aflizing bison
Mon Feb 15 05:54:04 2016: Reading package lists...
Mon Feb 15 05:54:04 2016: Building dependency tree...
Mon Feb 15 05:54:04 2016: Reading state information...
Mon Feb 15 05:54:04 2016: The following NEW packages will be installed:
Mon Feb 15 05:54:04 2016:   autotools-dev bsdmainutils debhelper dh-strip-nondeterminism file gettext
Mon Feb 15 05:54:04 2016:   gettext-base groff-base intltool-debian libarchive-zip-perl libcroco3
Mon Feb 15 05:54:04 2016:   libfile-stripnondeterminism-perl libmagic1 libpipeline1 libsigsegv2
Mon Feb 15 05:54:04 2016:   libtimedate-perl libunistring0 libxml2 m4 man-db po-debconf
Mon Feb 15 05:54:05 2016: 0 upgraded, 21 newly installed, 0 to remove and 63 not upgraded.
Mon Feb 15 05:54:05 2016: E: The package index files are corrupted. No Filename: field for package libpipeline1.
Mon Feb 15 05:54:05 2016: E: Failed to process build dependencies
Mon Feb 15 05:54:05 2016: Reading package lists...
Mon Feb 15 05:54:05 2016: Building dependency tree...
Mon Feb 15 05:54:05 2016: Reading state information...
Mon Feb 15 05:54:05 2016: The following NEW packages will be installed:
Mon Feb 15 05:54:05 2016:   autotools-dev bsdmainutils debhelper dh-strip-nondeterminism file gettext
Mon Feb 15 05:54:05 2016:   gettext-base groff-base intltool-debian libarchive-zip-perl libcroco3
Mon Feb 15 05:54:05 2016:   libfile-stripnondeterminism-perl libmagic1 libpipeline1 libsigsegv2
Mon Feb 15 05:54:05 2016:   libtimedate-perl libunistring0 libxml2 m4 man-db po-debconf
Mon Feb 15 05:54:06 2016: 0 upgraded, 21 newly installed, 0 to remove and 63 not upgraded.
Mon Feb 15 05:54:06 2016: E: The package index files are corrupted. No Filename: field for package libpipeline1.
Mon Feb 15 05:54:06 2016: E: Failed to process build dependencies
Mon Feb 15 05:54:06 2016: Breaking.
Failed do download dependencies for bison.
```

Looks like some docker users encountered this similar issue as well.
https://github.com/docker/docker/issues/19757

I don't really understand this issue. However, "apt-get upgrade" fixed it, fyi.

**Comment by d33tah** [comment] 2016-02-15 07:18
W dniu 15.02.2016 o 07:07, Kuang-che Wu pisze:

> failed to run sample command
> 
> ```
> (inside d33tah/afl-sid of image version id 99e736835753)
> # aflize bison
> ```
> 
> ```
> Mon Feb 15 05:54:03 2016: Aflizing bison
> Mon Feb 15 05:54:04 2016: Reading package lists...
> Mon Feb 15 05:54:04 2016: Building dependency tree...
> Mon Feb 15 05:54:04 2016: Reading state information...
> Mon Feb 15 05:54:04 2016: The following NEW packages will be installed:
> Mon Feb 15 05:54:04 2016:   autotools-dev bsdmainutils debhelper dh-strip-nondeterminism file gettext
> Mon Feb 15 05:54:04 2016:   gettext-base groff-base intltool-debian libarchive-zip-perl libcroco3
> Mon Feb 15 05:54:04 2016:   libfile-stripnondeterminism-perl libmagic1 libpipeline1 libsigsegv2
> Mon Feb 15 05:54:04 2016:   libtimedate-perl libunistring0 libxml2 m4 man-db po-debconf
> Mon Feb 15 05:54:05 2016: 0 upgraded, 21 newly installed, 0 to remove and 63 not upgraded.
> Mon Feb 15 05:54:05 2016: E: The package index files are corrupted. No Filename: field for package libpipeline1.
> Mon Feb 15 05:54:05 2016: E: Failed to process build dependencies
> Mon Feb 15 05:54:05 2016: Reading package lists...
> Mon Feb 15 05:54:05 2016: Building dependency tree...
> Mon Feb 15 05:54:05 2016: Reading state information...
> Mon Feb 15 05:54:05 2016: The following NEW packages will be installed:
> Mon Feb 15 05:54:05 2016:   autotools-dev bsdmainutils debhelper dh-strip-nondeterminism file gettext
> Mon Feb 15 05:54:05 2016:   gettext-base groff-base intltool-debian libarchive-zip-perl libcroco3
> Mon Feb 15 05:54:05 2016:   libfile-stripnondeterminism-perl libmagic1 libpipeline1 libsigsegv2
> Mon Feb 15 05:54:05 2016:   libtimedate-perl libunistring0 libxml2 m4 man-db po-debconf
> Mon Feb 15 05:54:06 2016: 0 upgraded, 21 newly installed, 0 to remove and 63 not upgraded.
> Mon Feb 15 05:54:06 2016: E: The package index files are corrupted. No Filename: field for package libpipeline1.
> Mon Feb 15 05:54:06 2016: E: Failed to process build dependencies
> Mon Feb 15 05:54:06 2016: Breaking.
> Failed do download dependencies for bison.
> ```
> 
> Looks like some docker users encountered this similar issue as well.
> https://github.com/docker/docker/issues/19757
> 
> I don't really understand this issue. However, "apt-get upgrade" fixed it, fyi.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/d33tah/aflize/issues/2

Looks like a temporary Debian Sid problem - it worked fine for me.

**Comment by d33tah** [comment] 2016-02-15 10:36
Closing until this one gets confirmed by someone else.

**Closed as completed by d33tah** 2016-02-15 10:36 UTC

**Comment by kcwu** [comment] 2016-02-15 10:46
confirmed. Now it works for me, too.
Thanks.
